[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=devel:devel

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:kasmvnc]
command=vncserver %(ENV_DISPLAY)s
    -depth %(ENV_VNC_COL_DEPTH)s
    -geometry %(ENV_VNC_RESOLUTION)s
    -websocketPort %(ENV_KASM_PORT)s
    -interface 0.0.0.0
    -BlacklistThreshold=0
    -FreeKeyMappings
    -select-de manual
    -fg
user=devel
autostart=true
autorestart=true
startretries=5
priority=10
stdout_logfile=/var/log/supervisor/kasmvnc-stdout.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=1
stderr_logfile=/var/log/supervisor/kasmvnc-stderr.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=1

[program:supercronic]
command=/usr/local/bin/supercronic-launcher
user=devel
autostart=true
autorestart=true
startretries=5
priority=40
stdout_logfile=/var/log/supervisor/supercronic-stdout.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=1
stderr_logfile=/var/log/supervisor/supercronic-stderr.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=1

[program:log-tail]
command=tail -n 0 -F
    /var/log/supervisor/kasmvnc-stdout.log
    /var/log/supervisor/kasmvnc-stderr.log
    /var/log/supervisor/supercronic-stdout.log
    /var/log/supervisor/supercronic-stderr.log
user=devel
autostart=true
autorestart=true
priority=50
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[include]
files = /etc/supervisor/conf.d/*.conf
